package client;

import java.sql.Timestamp;

/**
 * Generated by jDBMapLite-Generator
 */
public class User {

	private int userKey;
	private String userName;
	private String userID;
	private Timestamp createdAt;
	private int createdBy;
	private String isArchivedFlag;

	/**
	 * Default constructor.
	 */
	public User() {
		super();
	}

	public void setUserKey(int userKey) {
		this.userKey = userKey;
	}

	public int getUserKey() {
		return userKey;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUserID() {
		return userID;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getCreatedAt() {
		return createdAt;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getCreatedBy() {
		return createdBy;
	}

	public void setIsArchivedFlag(String isArchivedFlag) {
		this.isArchivedFlag = isArchivedFlag;
	}

	public String getIsArchivedFlag() {
		return isArchivedFlag;
	}

}