package jweblitebulletin.backend.data;

import java.sql.SQLException;
import java.util.List;

import jdbmaplite.db.JDBMapLiteManager;
import jdbmaplite.db.ParseConfigException;
import jdbmaplite.db.mapper.JDBMapLiteDao;

/**
 * Generated by jDBMapLite-Generator
 */
public class UserDao extends JDBMapLiteDao {

	/**
	 * Default constructor.
	 */
	public UserDao(JDBMapLiteManager dbManager) throws ParseConfigException {
		super(dbManager);
	}

	/**
	 * Get User
	 */
	public User getUser(String condition) throws SQLException {
		return (User) executeQuery("getUser", condition);
	}

	/**
	 * Get Users
	 */
	public List<User> getUsers() throws SQLException {
		return (List<User>) executeBulkQuery("getUsers");
	}

	/**
	 * Update User
	 */
	public void updateUser(String condition, String updateData)
			throws SQLException {
		executeUpdate("updateUser", condition, updateData);
	}

	/**
	 * Create User
	 */
	public void createUser(User user) throws SQLException {
		executeObjectUpdate("createUser", user);
	}

}